# Copyright 2024 Braden Ganetsky
# Distributed under the Boost Software License, Version 1.0.
# https://www.boost.org/LICENSE_1_0.txt

name: CI

on: 
  workflow_dispatch:
  pull_request:

jobs:
  build-msvc-vs2022:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Build tok3n
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" --preset all ..
          cmake --build . -j8

      - name: Run tok3n tests
        run: |
          cd build
          ctest --output-on-failure

  build-clang:
    strategy:
      matrix:
        include:
          - clang-version: 16
            os: ubuntu-22.04
          - clang-version: 17
            os: ubuntu-24.04
          - clang-version: 18
            os: ubuntu-24.04
          - clang-version: 19
            os: ubuntu-24.04

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Set up Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{matrix.clang-version}}
          sudo apt-get install -y \
            libc++-${{matrix.clang-version}}-dev \
            libc++abi-${{matrix.clang-version}}-dev

      - name: Build tok3n
        run: |
          mkdir build
          cd build
          cmake .. \
            --preset all \
            -DCMAKE_CXX_COMPILER=clang++-${{matrix.clang-version}}
          cmake --build . -j8

      - name: Run tok3n tests
        run: |
          cd build
          ctest --output-on-failure

  build-gcc:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        gcc-version: [12, 13, 14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Set up GCC
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt-get install -y \
            gcc-${{matrix.gcc-version}} \
            g++-${{matrix.gcc-version}} \
            libstdc++-${{matrix.gcc-version}}-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{matrix.gcc-version}} 999
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${{matrix.gcc-version}} 999

      - name: Build tok3n
        run: |
          mkdir build
          cd build
          cmake --preset all ..
          cmake --build . -j8

      - name: Run tok3n tests
        run: |
          cd build
          ctest --output-on-failure
