# Copyright 2024-2025 Braden Ganetsky
# Distributed under the Boost Software License, Version 1.0.
# https://www.boost.org/LICENSE_1_0.txt

name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-msvc-vs2022:
    strategy:
      matrix:
        cxx-standard: [20, 23]

    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Build tok3n
        run: |
          cmake --preset all `
            -B build `
            -G "Visual Studio 17 2022" `
            -DTOK3N_CXX_STANDARD=${{matrix.cxx-standard}} `
            -DTOK3N_CXX_WARNINGS=msvc
          cmake --build build -j16

      - name: Run tok3n tests
        run: |
          ctest --test-dir build --output-on-failure

  build-clang:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/k3dw/clang:${{matrix.clang-version}}

    strategy:
      matrix:
        clang-version: [16, 17, 18, 19, 20, 21, 22]
        cxx-standard: [20, 23]
        exclude:
          # There's some libc++ error for some reason
          - clang-version: 19
            cxx-standard: 23

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Build tok3n
        run: |
          cmake --preset all \
            -B build \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
            -DTOK3N_CXX_STANDARD=${{matrix.cxx-standard}} \
            -DTOK3N_CXX_WARNINGS=clang
          cmake --build build -j16

      - name: Run tok3n tests
        run: |
          ctest --test-dir build --output-on-failure

  build-gcc:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        gcc-version: [12, 13, 14]
        cxx-standard: [20, 23]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Set up GCC
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt-get install -y \
            gcc-${{matrix.gcc-version}} \
            g++-${{matrix.gcc-version}} \
            libstdc++-${{matrix.gcc-version}}-dev

      - name: Build tok3n
        run: |
          cmake --preset all \
            -B build \
            -DCMAKE_CXX_COMPILER=g++-${{matrix.gcc-version}} \
            -DTOK3N_CXX_STANDARD=${{matrix.cxx-standard}} \
            -DTOK3N_CXX_WARNINGS=gcc
          cmake --build build -j16

      - name: Run tok3n tests
        run: |
          ctest --test-dir build --output-on-failure
