# Copyright 2024-2026 Braden Ganetsky
# Distributed under the Boost Software License, Version 1.0.
# https://www.boost.org/LICENSE_1_0.txt

name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-msvc:
    strategy:
      matrix:
        cxx-standard: [20, 23]
        github-runner: [windows-2022, windows-2025]
        include:
          - github-runner: windows-2022
            cmake-generator: "Visual Studio 17 2022"
          - github-runner: windows-2025
            cmake-generator: "Visual Studio 18 2026"

    runs-on: ${{matrix.github-runner}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
            submodules: recursive

      - name: Build tok3n
        run: |
          cmake --preset all `
            -B build `
            -G "${{matrix.cmake-generator}}" `
            -DTOK3N_CXX_STANDARD=${{matrix.cxx-standard}} `
            -DTOK3N_CXX_WARNINGS=msvc
          cmake --build build -j2

      - name: Run tok3n tests
        run: |
          ctest --test-dir build --output-on-failure

  build-clang:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/k3dw/clang:${{matrix.clang-version}}

    strategy:
      matrix:
        clang-version: [16, 17, 18, 19, 20, 21, 22]
        cxx-standard: [20, 23]
        exclude:
          # There's some libc++ error for some reason
          - clang-version: 19
            cxx-standard: 23

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
            submodules: recursive

      - name: Build tok3n
        run: |
          cmake --preset all \
            -B build \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
            -DTOK3N_CXX_STANDARD=${{matrix.cxx-standard}} \
            -DTOK3N_CXX_WARNINGS=clang
          cmake --build build -j4

      - name: Run tok3n tests
        run: |
          ctest --test-dir build --output-on-failure

  build-gcc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/k3dw/gcc:${{matrix.gcc-version}}

    strategy:
      matrix:
        gcc-version: [12, 13, 14, 15, 16]
        cxx-standard: [20, 23]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
            submodules: recursive

      - name: Build tok3n
        run: |
          cmake --preset all \
            -B build \
            -DCMAKE_CXX_COMPILER=g++ \
            -DTOK3N_CXX_STANDARD=${{matrix.cxx-standard}} \
            -DTOK3N_CXX_WARNINGS=gcc
          cmake --build build -j4

      - name: Run tok3n tests
        run: |
          ctest --test-dir build --output-on-failure
